#!/usr/bin/env bash
# This script installs and configures Nginx to serve 'Hello World' at the root URL.
# Install Nginx using apt-get
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to serve the 'Hello World!' page.
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	server_name _;

	location / {
		try_files \$uri/ =404;
	}
}
EOF

# Reload Nginx to apply the changes (without using systemctl)
sudo service nginx reload
