#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with a 301 Moved Permanently response.

# Install Nginx if it's not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Start Nginx if it's not already running
if ! sudo serivice nginx status; then
	sudo service nginx start
fi

# Configure Nginx to redirect /redirect_me
sudo sed -i 'server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo sservice nginx reload
