#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with a 301 Moved Permanently response

# Install Nginx if it's not already installed
sudo apt-get update -y
sudo apt-get install -y nginx

# Configure Nginx to add redirect rule if not exists
echo 'Hello World!' > /var/www/html/index.html

# update config file to redirect
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 http://google.com/;
    }
}" > /etc/nginx/sites-available/default

# Start nginx after reloading config
service nginx start
