#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with a 301 Moved Permanently response

# Install Nginx if it's not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Start Nginx if it's not already running
if ! sudo service nginx status; then
    sudo service nginx start
fi

# Start Nginx if it's not already running
if ! sudo service nginx status; then
    sudo service nginx start
fi

# Configure Nginx to redirect /redirect_me
if ! grep -q '/redirect_me' /etc/nginx/sites-available/default; then
	sudo sed -i '/server_name _;/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default
fi

# Reload Nginx configuration (without using systemctl)
sudo service nginx reload
