#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with a 301 Moved Permanently response

# Install Nginx if it's not already installed
sudo apt-get update -y
sudo apt-get install -y nginx

# Configure Nginx to add redirect rule if not exists
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/not_found_404.html

# Update config file to redirect
printf %s "server {
	listen 80;
	listen [::]:80 default_server;
       	root   /var/www/html;
	index  index.html index.htm index.nginx-debian.html;
	
	location /redirect_me {
        	return 301 http://google.com/;
	}

	error_page 404 /not_found_404.html;
	location /not_found_404 {
		root /var/www/html;
		internal;
	}
    
}" > /etc/nginx/sites-available/default

# Start nginx after reloading config
service nginx start 
