#!/usr/bin/env bash
# Bash script that displays a list of currently running processes.
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Display process hierarchy
ps axjf
