#!/bin/bash

# Check if the script is run as root 
if [ "$(id -u)" != "0" ]; then
	echo "Error: This script must be run as root" 1>&2
	exit
fi

# Check the number of arguments
if [ "$#" -ne 1 ]; then
	echo "Usage: $0 {start|stop|restart}"
	exit  1
fi

# Execute manage_my_process script with the specified argument
./manage_my_process "$1"
