#!/bin/bash

# Find the process ID of 7-highlander
highlander_pid=$(pgrep -f "7-highlander")

# Check if the process ID was found
if [ -n "$highlander_pid" ]; then
	# Kill the process
	kill "$highlander_pid"
	echo "Killed 7-highlander"
else
	echo "7-highlander process not found"
fi
